import type { StudentResult, Exam } from "@/types/result";
import type { StudentFee, FeePayment } from "@/types/fee";
import { formatPKR } from "@/types/fee";
import type { PaperState } from "@/types/paper";

const WHATSAPP_BASE = "https://wa.me";

function openWhatsApp(phone: string, text: string) {
  const encoded = encodeURIComponent(text);
  const url = phone ? `${WHATSAPP_BASE}/${phone.replace(/[^0-9]/g, "")}?text=${encoded}` : `${WHATSAPP_BASE}?text=${encoded}`;
  window.open(url, "_blank");
}

async function generatePdfBlob(element: HTMLElement): Promise<Blob | null> {
  try {
    const html2canvasMod = await import("html2canvas");
    const h2c = html2canvasMod.default || html2canvasMod;
    const jsPdfMod = await import("jspdf");
    const JsPDF = jsPdfMod.default || jsPdfMod.jsPDF;

    const canvas = await h2c(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      logging: false,
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new JsPDF("p", "mm", "a4");
    const pdfWidth = 210;
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    if (pdfHeight > 297) {
      const pageHeight = 297;
      let heightLeft = pdfHeight;
      let position = 0;

      pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;

      while (heightLeft > 0) {
        position -= pageHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
        heightLeft -= pageHeight;
      }
    } else {
      pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    }

    return pdf.output("blob");
  } catch (err) {
    console.error("PDF generation failed:", err);
    return null;
  }
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

async function sharePdfViaWhatsApp(
  elementId: string,
  filename: string,
  phone: string,
  caption: string
): Promise<boolean> {
  const el = document.getElementById(elementId);
  if (!el) return false;

  const blob = await generatePdfBlob(el);
  if (!blob) return false;

  const file = new File([blob], filename, { type: "application/pdf" });

  // Mobile: Web Share API (directly opens WhatsApp with file attached)
  if (navigator.share && navigator.canShare?.({ files: [file] })) {
    try {
      await navigator.share({
        files: [file],
        title: filename,
        text: caption,
      });
      return true;
    } catch (err) {
      if ((err as Error).name === "AbortError") return false;
      // Fall through to download approach
    }
  }

  // Desktop: Download PDF + open WhatsApp with caption
  downloadBlob(blob, filename);
  openWhatsApp(phone, caption + "\n\n(PDF downloaded — attach it manually in WhatsApp)");
  return true;
}

// ─── Text-only share (unchanged) ────────────────────────────────────────────

export function shareResultWhatsApp(student: StudentResult, exam: Exam | null, schoolName: string, phone?: string) {
  const examName = exam?.name || "Examination";
  const className = exam?.className || "";

  let msg = `*${schoolName}*\n`;
  msg += `${examName}${className ? ` — Class ${className}` : ""}\n\n`;
  msg += `*${student.studentName}* (Roll: ${student.rollNo})\n`;
  msg += `Position: ${ordinal(student.position)}\n`;
  msg += `Grade: ${student.grade}\n`;
  msg += `Total: ${student.totalObtained}/${student.totalMarks} (${student.percentage}%)\n`;
  msg += `Status: ${student.passed ? "PASS ✅" : "FAIL ❌"}\n\n`;

  if (exam?.subjects && exam.subjects.length > 0) {
    msg += `*Subject-wise Marks:*\n`;
    for (const sub of exam.subjects) {
      const obtained = student.subjectMarks[sub.name] ?? 0;
      const subPassed = obtained >= sub.passingMarks;
      msg += `${sub.name}: ${obtained}/${sub.totalMarks} ${subPassed ? "✅" : "❌"}\n`;
    }
    msg += "\n";
  }

  msg += `Generated by AI Voice Paper Maker`;
  openWhatsApp(phone || "", msg);
}

export function shareAllResultsWhatsApp(results: StudentResult[], exam: Exam | null, schoolName: string) {
  if (results.length === 0) return;

  const examName = exam?.name || "Examination";
  const className = exam?.className || "";

  let msg = `*${schoolName}*\n`;
  msg += `*${examName}* Results${className ? ` — Class ${className}` : ""}\n`;
  msg += `Total Students: ${results.length}\n\n`;

  const passed = results.filter((r) => r.passed).length;
  const avg = results.reduce((s, r) => s + r.percentage, 0) / results.length;
  msg += `Pass: ${passed}/${results.length}\n`;
  msg += `Average: ${avg.toFixed(1)}%\n\n`;

  const sorted = [...results].sort((a, b) => a.position - b.position);
  msg += `*Results:*\n`;
  for (const r of sorted.slice(0, 30)) {
    msg += `${ordinal(r.position)} ${r.studentName}: ${r.totalObtained}/${r.totalMarks} (${r.percentage}%) — ${r.passed ? "PASS" : "FAIL"}\n`;
  }
  if (sorted.length > 30) msg += `...aur ${sorted.length - 30} students\n`;

  msg += `\nGenerated by AI Voice Paper Maker`;
  openWhatsApp("", msg);
}

// ─── PDF share (report card → WhatsApp with PDF attached) ────────────────────

export async function shareReportCardPdfWhatsApp(
  studentName: string,
  examName: string,
  phone?: string
): Promise<boolean> {
  const filename = `${examName}-${studentName}-report-card.pdf`;
  const caption = `${studentName} — ${examName} Report Card\nGenerated by AI Voice Paper Maker`;
  return sharePdfViaWhatsApp("report-card-preview-content", filename, phone || "", caption);
}

// ─── PDF share (paper → WhatsApp with PDF attached) ──────────────────────────

export async function sharePaperPdfWhatsApp(
  paper: PaperState,
  phone?: string
): Promise<boolean> {
  const title = paper.paperTitle || "paper";
  const filename = `${paper.schoolName || "school"}-${title}.pdf`;
  const caption = `Paper: ${title}\nSubject: ${paper.subject || "N/A"}\nClass: ${paper.className || "N/A"}\nQuestions: ${paper.questions.length}\n\nGenerated by AI Voice Paper Maker`;
  return sharePdfViaWhatsApp("paper-preview", filename, phone || "", caption);
}

// ─── PDF share (result sheet → WhatsApp with PDF attached) ───────────────────

export async function shareResultSheetPdfWhatsApp(
  examName: string,
  className: string,
  phone?: string
): Promise<boolean> {
  const filename = `${examName}-${className}-result-sheet.pdf`;
  const caption = `Result Sheet: ${examName} — Class ${className}\nGenerated by AI Voice Paper Maker`;
  return sharePdfViaWhatsApp("result-sheet-content", filename, phone || "", caption);
}

// ─── Plain text (paper) ─────────────────────────────────────────────────────

export function sharePaperWhatsApp(paper: PaperState, phone?: string) {
  let msg = `*Paper — ${paper.schoolName || "School"}*\n`;
  if (paper.paperTitle) msg += `Title: ${paper.paperTitle}\n`;
  if (paper.subject) msg += `Subject: ${paper.subject}\n`;
  if (paper.className) msg += `Class: ${paper.className}\n`;
  if (paper.time) msg += `Time: ${paper.time}\n`;
  if (paper.totalMarks) msg += `Total Marks: ${paper.totalMarks}\n`;
  if (paper.date) msg += `Date: ${paper.date}\n`;
  msg += `\n*Questions (${paper.questions.length}):*\n`;

  for (let i = 0; i < paper.questions.length; i++) {
    const q = paper.questions[i];
    msg += `${i + 1}. [${q.type.toUpperCase()}] ${q.text}`;
    if (q.options && q.options.length > 0) {
      msg += "\n   Options: " + q.options.join(", ");
    }
    msg += "\n";
  }

  msg += `\nGenerated by AI Voice Paper Maker`;
  openWhatsApp(phone || "", msg);
}

// ─── Fee Slip WhatsApp share ─────────────────────────────────────────────────

export function shareFeeSlipWhatsApp(
  student: StudentFee,
  payment: FeePayment,
  schoolName: string
) {
  const balance = payment.amount_due - payment.amount_paid;
  const statusEmoji =
    payment.status === "paid" ? "✅ PAID" :
    payment.status === "partial" ? "⚠️ PARTIAL" : "❌ DUE";

  let msg = `🏫 *${schoolName}*\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `📋 *Fee Notification Slip*\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n\n`;
  msg += `👤 *Student:* ${student.student_name}\n`;
  if (student.father_name) msg += `👨 *Father:* ${student.father_name}\n`;
  msg += `🏛️ *Class:* ${student.class_name}${student.section ? `-${student.section}` : ""}`;
  if (student.roll_no) msg += ` | Roll No: ${student.roll_no}`;
  msg += `\n📅 *Month:* ${payment.month_label}\n\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `💰 *Fee Due:*   ${formatPKR(payment.amount_due)}\n`;
  msg += `✅ *Paid:*      ${formatPKR(payment.amount_paid)}\n`;
  msg += `📊 *Balance:*   ${formatPKR(balance)}\n`;
  msg += `🔖 *Status:*    ${statusEmoji}\n`;
  if (payment.payment_date) msg += `📆 *Date:*      ${payment.payment_date}\n`;
  if (payment.remarks) msg += `📝 *Note:*      ${payment.remarks}\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━━\n\n`;
  if (payment.status !== "paid") {
    msg += `⏰ Meherbani farma ke jald az jald fee ada karein.\n\n`;
  } else {
    msg += `Shukriya! Fee ada karne ka shukriya. 🙏\n\n`;
  }
  msg += `_${schoolName}_`;

  openWhatsApp(student.parent_phone || "", msg);
}

function ordinal(n: number): string {

  if (n === 0) return "";
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
