import type { StudentResult, Exam } from "@/types/result";
import type { PaperState } from "@/types/paper";

const WHATSAPP_BASE = "https://wa.me";

function openWhatsApp(phone: string, text: string) {
  const encoded = encodeURIComponent(text);
  const url = phone ? `${WHATSAPP_BASE}/${phone.replace(/[^0-9]/g, "")}?text=${encoded}` : `${WHATSAPP_BASE}?text=${encoded}`;
  window.open(url, "_blank");
}

export function shareResultWhatsApp(student: StudentResult, exam: Exam | null, schoolName: string, phone?: string) {
  const examName = exam?.name || "Examination";
  const className = exam?.className || "";

  let msg = `*${schoolName}*\n`;
  msg += `${examName}${className ? ` — Class ${className}` : ""}\n\n`;
  msg += `*${student.studentName}* (Roll: ${student.rollNo})\n`;
  msg += `Position: ${ordinal(student.position)}\n`;
  msg += `Grade: ${student.grade}\n`;
  msg += `Total: ${student.totalObtained}/${student.totalMarks} (${student.percentage}%)\n`;
  msg += `Status: ${student.passed ? "PASS ✅" : "FAIL ❌"}\n\n`;

  if (exam?.subjects && exam.subjects.length > 0) {
    msg += `*Subject-wise Marks:*\n`;
    for (const sub of exam.subjects) {
      const obtained = student.subjectMarks[sub.name] ?? 0;
      const subPassed = obtained >= sub.passingMarks;
      msg += `${sub.name}: ${obtained}/${sub.totalMarks} ${subPassed ? "✅" : "❌"}\n`;
    }
    msg += "\n";
  }

  msg += `Generated by AI Voice Paper Maker`;

  openWhatsApp(phone || "", msg);
}

export function shareAllResultsWhatsApp(results: StudentResult[], exam: Exam | null, schoolName: string) {
  if (results.length === 0) return;

  const examName = exam?.name || "Examination";
  const className = exam?.className || "";

  let msg = `*${schoolName}*\n`;
  msg += `*${examName}* Results${className ? ` — Class ${className}` : ""}\n`;
  msg += `Total Students: ${results.length}\n\n`;

  const passed = results.filter((r) => r.passed).length;
  const avg = results.reduce((s, r) => s + r.percentage, 0) / results.length;
  msg += `Pass: ${passed}/${results.length}\n`;
  msg += `Average: ${avg.toFixed(1)}%\n\n`;

  const sorted = [...results].sort((a, b) => a.position - b.position);
  msg += `*Results:*\n`;
  for (const r of sorted.slice(0, 30)) {
    msg += `${ordinal(r.position)} ${r.studentName}: ${r.totalObtained}/${r.totalMarks} (${r.percentage}%) — ${r.passed ? "PASS" : "FAIL"}\n`;
  }
  if (sorted.length > 30) msg += `...aur ${sorted.length - 30} students\n`;

  msg += `\nGenerated by AI Voice Paper Maker`;

  openWhatsApp("", msg);
}

export function sharePaperWhatsApp(paper: PaperState, phone?: string) {
  let msg = `*Paper — ${paper.schoolName || "School"}*\n`;
  if (paper.paperTitle) msg += `Title: ${paper.paperTitle}\n`;
  if (paper.subject) msg += `Subject: ${paper.subject}\n`;
  if (paper.className) msg += `Class: ${paper.className}\n`;
  if (paper.time) msg += `Time: ${paper.time}\n`;
  if (paper.totalMarks) msg += `Total Marks: ${paper.totalMarks}\n`;
  if (paper.date) msg += `Date: ${paper.date}\n`;
  msg += `\n*Questions (${paper.questions.length}):*\n`;

  for (let i = 0; i < paper.questions.length; i++) {
    const q = paper.questions[i];
    msg += `${i + 1}. [${q.type.toUpperCase()}] ${q.text}`;
    if (q.options && q.options.length > 0) {
      msg += "\n   Options: " + q.options.join(", ");
    }
    msg += "\n";
  }

  msg += `\nGenerated by AI Voice Paper Maker`;
  openWhatsApp(phone || "", msg);
}

function ordinal(n: number): string {
  if (n === 0) return "";
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
